# See config.example.yml for documentation.
object: orig/GSAP01-DEBUG/default.dol
hash: 77d1a4fad2a420bfcc5e6217266bc698542df20e
name: default
symbols: config/GSAP01-DEBUG/symbols.txt
splits: config/GSAP01-DEBUG/splits.txt

# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 8
ldscript_template: config/GSAP01-DEBUG/ldscript.tpl

# no .rel files here.
#modules:
#- object: orig/GAMEID/files/module.rel
#  hash: 0123456789abcdef0123456789abcdef01234567
#  symbols: config/GAMEID/module/symbols.txt
#  splits: config/GAMEID/module/splits.txt

#extract:
#- # The symbol name to extract.
#  symbol: SomeSymbol
#
#  # (optional) The path to extract raw binary data to.
#  # Path is relative to `build/GAMEID/bin`.
#  binary: Lib/SomeSymbol.bin
#
#  # (optional) The path to extract a C array representation to.
#  # In a C/C++ file, the symbol can be included with `#include "Lib/SomeSymbol.inc"`.
#  # Path is relative to `build/GAMEID/include`.
#  header: Lib/SomeSymbol.inc
