#define LISTS_COL                1
#define SCREEN_COL               2
#define CODE_COL                 3
#define DLL_COL                  4
#define TRACK_COL                5
#define TEX_COL                  6
#define TRACKTEX_COL             7
#define SPRITETEX_COL            8
#define MODELS_COL               9
#define ANIMS_COL               10
#define AUDIO_COL               11
#define SEQ_COL                 12
#define SFX_COL                 13
#define OBJECTS_COL             14
#define CAM_COL                 15
#define VOX_COL                 16
#define ANIMSEQ_COL             17
#define LFX_COL                 18
#define GFX_COL                 19
#define EXPGFX_COL              20
#define MODGFX_COL              21
#define PROJGFX_COL             22
#define SKY_COL                 23
#define SHAD_COL                24
#define GAME_COL                25
#define TEST_COL                26
#define BLACK_COL               27
#define RED_COL                 28
#define GREEN_COL               29
#define BLUE_COL                30
#define CYAN_COL                31
#define MAGENTA_COL             32
#define YELLOW_COL              33
#define WHITE_COL               34
#define GREY_COL                35
#define ORANGE_COL              36
#define MODELINSTANCE_COL       37 //was 137, probably my typo
#define OBJECTS_COL_RGB         0x0000EEFF
#define VOX_COL_RGB             0x00880099
#define ANIMS_COL_RGB           0x008888FF
#define TRACK_COL_RGB           0x00EE00FF
#define MODELS_COL_RGB          0x00EEEEFF
#define GAME_COL_RGB            0x12345678
#define ANIMSEQ_COL_RGB         0x4050FFFF
#define FILE_COL_RGB            0x7D7D7D7D
#define CODE_COL_RGB            0x7E7E7EFE
#define SHAD_COL_RGB            0x7F7F7F99
#define COMPRESSED_FILE_COL_RGB 0x7F7F7FFF
#define CAM_COL_RGB             0x88000099
#define DLL_COL_RGB             0x8E8E8EFE
#define LISTS_COL_RGB           0xCECECEFE
#define SFX_COL_RGB             0xEE0000BB
#define SEQ_COL_RGB             0xEE0000DD
#define AUDIO_COL_RGB           0xEE0000FF
#define SPRITETEX_COL_RGB       0xEE00EE99
#define TRACKTEX_COL_RGB        0xEE00EECC
#define TEX_COL_RGB             0xEE00EEFF
#define SCREEN_COL_RGB          0xEEEEEEFE
#define FACEFEED_COL_RGB        0xFACEFEED
#define SKY_COL_RGB             0xFF3300FF
#define PROJGFX_COL_RGB         0xFF5500FF
#define MODGFX_COL_RGB          0xFF7700FF
#define EXPGFX_COL_RGB          0xFF9900FF
#define GFX_COL_RGB             0xFFAA00FF
#define LFX_COL_RGB             0xFFCC00FF
#define TEST_COL_RGB            0xFFDD00FF
#define INTERSECT_POINT_COL_RGB 0xFFFF00FF
#define SAVEGAME_COL_RGB        0xFFFFFFFF
