#define MapId_frontend 0
#define MapId_frontend2 1
#define MapId_dragrock 2
#define MapId_krazoapalace 3
#define MapId_temple 4
#define MapId_hightop 5
#define MapId_discovery 6
#define MapId_hollow 7
#define MapId_hollow2 8
#define MapId_mazecave 9
#define MapId_wastes 10
#define MapId_warlock 11
#define MapId_fortress 12
#define MapId_wallcity 13
#define MapId_swapcircle 14
#define MapId_cloudtreasure 15
#define MapId_clouddungeon 16
#define MapId_cloudtrap 17
#define MapId_moonpass 18
#define MapId_snowmines 19
#define MapId_krashrin2 20
#define MapId_kraztest 21
#define MapId_krazchamber 22
#define MapId_newicemount 23
#define MapId_newicemount2 24
#define MapId_newicemount3 25
#define MapId_animtest 26
#define MapId_snowmines2 27
#define MapId_snowmines3 28
#define MapId_capeclaw 29
#define MapId_insidegal 30
#define MapId_dfshrine 31
#define MapId_mmshrine 32
#define MapId_ecshrine 33
#define MapId_gpshrine 34
#define MapId_diamondbay 35
#define MapId_earthwalker 36
#define MapId_willow 37
#define MapId_arwing 38
#define MapId_dbshrine 39
#define MapId_nwshrine 40
#define MapId_ccshrine 41
#define MapId_wgshrine 42
#define MapId_cloudrace 43
#define MapId_finalboss 44
#define MapId_wminsert 45
#define MapId_snowmines4 46
#define MapId_snowmines5 47
#define MapId_trexboss 48
#define MapId_mikelava 49
#define MapId_dfptop 50
#define MapId_swapstore 51
#define MapId_dragbot 52
#define MapId_kamdrag 53
#define MapId_magicave 54
#define MapId_duster 55
#define MapId_linkb 56
#define MapId_cloudjoin 57
#define MapId_arwingtoplanet 58
#define MapId_arwingdarkice 59
#define MapId_arwingcloud 60
#define MapId_arwingcity 61
#define MapId_arwingdragon 62
#define MapId_gamefront 63
#define MapId_linklevel 64
#define MapId_greatfox 65
#define MapId_linka 66
#define MapId_linkc 67
#define MapId_linkd 68
#define MapId_linke 69
#define MapId_linkf 70
#define MapId_linkg 71
#define MapId_linkh 72
#define MapId_linkj 73
#define MapId_linki 74
#define MapId_dfpodium 75
#define MapId_dfcradle 76
#define MapId_dfcavehatch1 77
#define MapId_dfcavehatch2 78
#define MapId_scstatue 79
#define MapId_galleonship 80
#define MapId_cfgalleon 81
#define MapId_cfgangplank 82
#define MapId_nwtreebridge 83
#define MapId_cfdungeonblock 84
#define MapId_cloudrunnermap 85
#define MapId_ccbridge 86
#define MapId_cfcolumn 87
#define MapId_nwboulder 88
#define MapId_cfprisondoor 89
#define MapId_cfprisoncage 90
#define MapId_nwtreebridge2 91
#define MapId_dim2iceblock1 92
#define MapId_dimpushblock 93
#define MapId_dim2iceblock2 94
#define MapId_dimhornplinth 95
#define MapId_nwshcolpush 96
#define MapId_dim2lift 97
#define MapId_dim2icefloe 98
#define MapId_dim2icefloe1 99
#define MapId_dim2icefloe2 100
#define MapId_cfliftplat 101
#define MapId_imspacecraft 102
#define MapId_dimbossgut 103
#define MapId_wmcolrise 104
#define MapId_vfpslide1 105
#define MapId_vfpslide2 106
#define MapId_drpushcart 107
#define MapId_drliftplat 108
#define MapId_dim2stonepillar 109
#define MapId_bossdrakorflatr 110
#define MapId_wcbouncycrate 111
#define MapId_wcpushblock 112
#define MapId_wctemplelift 113
#define MapId_KamColumn 114
#define MapId_dbstepstone 115
#define MapId_vfppushblock 116
#define MapId_None -1

