#ifndef _SYS_FILES_H_
#define _SYS_FILES_H_

#include "../types.h"

typedef uint DataFileLoadedFlags;
typedef enum { //different from final!
    //inconsistent suffix capitalization is
    //just how the game names them
    FILE_NONE = -1,
    FILE_AUDIO_tab = 0,
    FILE_AUDIO_bin = 1,
    FILE_SFX_tab = 2,
    FILE_SFX_bin = 3,
    FILE_AMBIENT_tab = 4,
    FILE_AMBIENT_bin = 5,
    FILE_MUSIC_tab = 6,
    FILE_MUSIC_bin = 7,
    FILE_MPEG_tab = 8,
    FILE_MPEG_bin = 9,
    FILE_MUSICACT_bin = 10,
    FILE_CAMACTIO_bin = 11,
    FILE_LACTIONS_bin = 12,
    FILE_ANIMCURV_bin = 13,
    FILE_ANIMCURV_tab = 14,
    FILE_OBJSEQ2C_tab = 15,
    FILE_FONTS_bin = 16,
    FILE_CACHEFON_bin = 17,
    FILE_CACHEFON_bin2 = 18,
    FILE_GAMETEXT_bin = 19,
    FILE_GAMETEXT_tab = 20,
    FILE_globalma_bin = 21,
    FILE_TABLES_bin = 22,
    FILE_TABLES_tab = 23,
    FILE_SCREENS_bin = 24,
    FILE_SCREENS_tab = 25,
    FILE_VOXMAP_tab = 26,
    FILE_VOXMAP_bin = 27,
    FILE_WARPTAB_bin = 28,
    FILE_MAPS_bin = 29,
    FILE_MAPS_tab = 30,
    FILE_MAPINFO_bin = 31,
    FILE_TEX1_bin = 32,
    FILE_TEX1_tab = 33,
    FILE_TEXTABLE_bin = 34,
    FILE_TEX0_bin = 35,
    FILE_TEX0_tab = 36,
    FILE_BLOCKS_bin = 37,
    FILE_BLOCKS_tab = 38,
    FILE_TRKBLK_tab = 39,
    FILE_HITS_bin = 40,
    FILE_HITS_tab = 41,
    FILE_MODELS_tab = 42,
    FILE_MODELS_bin = 43,
    FILE_MODELIND_bin = 44,
    FILE_MODANIM_TAB = 45,
    FILE_MODANIM_BIN = 46,
    FILE_ANIM_TAB = 47,
    FILE_ANIM_BIN = 48,
    FILE_AMAP_TAB = 49,
    FILE_AMAP_BIN = 50,
    FILE_BITTABLE_bin = 51,
    FILE_WEAPONDA_bin = 52,
    FILE_VOXOBJ_tab = 53,
    FILE_VOXOBJ_bin = 54,
    FILE_MODLINES_bin = 55,
    FILE_MODLINES_tab = 56,
    FILE_SAVEGAME_bin = 57,
    FILE_SAVEGAME_tab = 58,
    FILE_OBJSEQ_bin = 59,
    FILE_OBJSEQ_tab = 60,
    FILE_OBJECTS_tab = 61,
    FILE_OBJECTS_bin = 62,
    FILE_OBJINDEX_bin = 63,
    FILE_OBJEVENT_bin = 64,
    FILE_OBJHITS_bin = 65,
    FILE_DLLS_bin = 66,
    FILE_DLLS_tab = 67,
    FILE_DLLSIMPO_bin = 68,
    FILE_MODELS_tab2 = 69,
    FILE_MODELS_bin2 = 70,
    FILE_BLOCKS_bin2 = 71,
    FILE_BLOCKS_tab2 = 72,
    FILE_ANIM_TAB2 = 73,
    FILE_ANIM_BIN2 = 74,
    FILE_TEX1_bin2 = 75,
    FILE_TEX1_tab2 = 76,
    FILE_TEX0_bin2 = 77,
    FILE_TEX0_tab2 = 78,
    FILE_ENVFXACT_bin = 79,
    NUM_FILES = 80,
    FILE_NULL = 80,
    FILE_NULL2 = 81,
} DataFileId32;

#define MODELS_TAB_SIZE 0x800
#define ANIM_TAB_SIZE 3000 //not 0x3000
#define TEX0_TAB_SIZE 0x1000
#define TEX1_TAB_SIZE 0x1000
#define BLOCKS_TAB_SIZE 0x800

#endif //_SYS_FILES_H_
